export const binaryInputsDefinition = "BinaryInputExample DEFINITIONS ::= BEGIN\n\nBinaryRecord ::= SEQUENCE {\n  payload OCTET STRING,\n  label OCTET STRING OPTIONAL,\n  flags BIT STRING OPTIONAL\n}\n\nEND\n";

export const defaultsAndEnumeratedDefinition = "DefaultExample DEFINITIONS ::= BEGIN\n\nStatus ::= ENUMERATED {\n  ok(0),\n  warning(1),\n  failed(2)\n}\n\nDefaultRecord ::= SEQUENCE {\n  enabled BOOLEAN DEFAULT TRUE,\n  retryCount INTEGER DEFAULT 3,\n  status Status DEFAULT ok,\n  note UTF8String OPTIONAL\n}\n\nEND\n";

export const minimalCrlDefinition = "MinimalCrlExample DEFINITIONS EXPLICIT TAGS ::= BEGIN\n\nAlgorithmIdentifier ::= SEQUENCE {\n  algorithm OBJECT IDENTIFIER,\n  parameters NULL OPTIONAL\n}\n\nAttributeTypeAndValue ::= SEQUENCE {\n  type OBJECT IDENTIFIER,\n  value DirectoryString\n}\n\nDirectoryString ::= CHOICE {\n  utf8String UTF8String,\n  printableString PrintableString\n}\n\nRelativeDistinguishedName ::= SET OF AttributeTypeAndValue\n\nRDNSequence ::= SEQUENCE OF RelativeDistinguishedName\nName ::= CHOICE {\n  rdnSequence RDNSequence\n}\n\nTime ::= CHOICE {\n  utcTime UTCTime,\n  generalTime GeneralizedTime\n}\n\nExtension ::= SEQUENCE {\n  extnID OBJECT IDENTIFIER,\n  critical BOOLEAN DEFAULT FALSE,\n  extnValue OCTET STRING\n}\n\nExtensions ::= SEQUENCE OF Extension\n\nVersion ::= INTEGER {\n  v1(0),\n  v2(1)\n}\n\nRevokedCertificate ::= SEQUENCE {\n  userCertificate INTEGER,\n  revocationDate Time,\n  crlEntryExtensions Extensions OPTIONAL\n}\n\nRevokedCertificates ::= SEQUENCE OF RevokedCertificate\n\nTBSCertList ::= SEQUENCE {\n  version Version OPTIONAL,\n  signature AlgorithmIdentifier,\n  issuer Name,\n  thisUpdate Time,\n  nextUpdate Time OPTIONAL,\n  revokedCertificates RevokedCertificates OPTIONAL,\n  crlExtensions [0] EXPLICIT Extensions OPTIONAL\n}\n\nCertificateList ::= SEQUENCE {\n  tbsCertList TBSCertList,\n  signatureAlgorithm AlgorithmIdentifier,\n  signatureValue BIT STRING\n}\n\nEND\n";

export const minimalCsrDefinition = "MinimalCsrExample DEFINITIONS EXPLICIT TAGS ::= BEGIN\n\nAlgorithmIdentifier ::= SEQUENCE {\n  algorithm OBJECT IDENTIFIER,\n  parameters NULL OPTIONAL\n}\n\nAttributeTypeAndValue ::= SEQUENCE {\n  type OBJECT IDENTIFIER,\n  value DirectoryString\n}\n\nDirectoryString ::= CHOICE {\n  utf8String UTF8String,\n  printableString PrintableString\n}\n\nRelativeDistinguishedName ::= SET OF AttributeTypeAndValue\n\nRDNSequence ::= SEQUENCE OF RelativeDistinguishedName\nName ::= CHOICE {\n  rdnSequence RDNSequence\n}\n\nSubjectPublicKeyInfo ::= SEQUENCE {\n  algorithm AlgorithmIdentifier,\n  subjectPublicKey BIT STRING\n}\n\nAttributeValue ::= OCTET STRING\n\nAttributeValues ::= SET OF AttributeValue\n\nAttribute ::= SEQUENCE {\n  type OBJECT IDENTIFIER,\n  values AttributeValues\n}\n\nAttributes ::= SET OF Attribute\n\nCertificationRequestInfo ::= SEQUENCE {\n  version INTEGER,\n  subject Name,\n  subjectPublicKeyInfo SubjectPublicKeyInfo,\n  attributes [0] IMPLICIT Attributes\n}\n\nCertificationRequest ::= SEQUENCE {\n  certificationRequestInfo CertificationRequestInfo,\n  signatureAlgorithm AlgorithmIdentifier,\n  signature BIT STRING\n}\n\nEND\n";

export const minimalTbsCertificateDefinition = "MinimalCertificateExample DEFINITIONS EXPLICIT TAGS ::= BEGIN\n\nAlgorithmIdentifier ::= SEQUENCE {\n  algorithm OBJECT IDENTIFIER,\n  parameters NULL OPTIONAL\n}\n\nAttributeTypeAndValue ::= SEQUENCE {\n  type OBJECT IDENTIFIER,\n  value DirectoryString\n}\n\nDirectoryString ::= CHOICE {\n  utf8String UTF8String,\n  printableString PrintableString\n}\n\nRelativeDistinguishedName ::= SET OF AttributeTypeAndValue\n\nRDNSequence ::= SEQUENCE OF RelativeDistinguishedName\nName ::= CHOICE {\n  rdnSequence RDNSequence\n}\n\nTime ::= CHOICE {\n  utcTime UTCTime,\n  generalTime GeneralizedTime\n}\n\nValidity ::= SEQUENCE {\n  notBefore Time,\n  notAfter Time\n}\n\nSubjectPublicKeyInfo ::= SEQUENCE {\n  algorithm AlgorithmIdentifier,\n  subjectPublicKey BIT STRING\n}\n\nExtension ::= SEQUENCE {\n  extnID OBJECT IDENTIFIER,\n  critical BOOLEAN DEFAULT FALSE,\n  extnValue OCTET STRING\n}\n\nExtensions ::= SEQUENCE OF Extension\n\nVersion ::= INTEGER {\n  v1(0),\n  v2(1),\n  v3(2)\n}\n\nTBSCertificate ::= SEQUENCE {\n  version [0] EXPLICIT Version DEFAULT v1,\n  serialNumber INTEGER,\n  signature AlgorithmIdentifier,\n  issuer Name,\n  validity Validity,\n  subject Name,\n  subjectPublicKeyInfo SubjectPublicKeyInfo,\n  extensions [3] EXPLICIT Extensions OPTIONAL\n}\n\nCertificate ::= SEQUENCE {\n  tbsCertificate TBSCertificate,\n  signatureAlgorithm AlgorithmIdentifier,\n  signatureValue BIT STRING\n}\n\nEND\n";

export const moduleTagsDefinition = "ImplicitHeaderExample DEFINITIONS IMPLICIT TAGS ::= BEGIN\n\nVersion ::= INTEGER {\n  v1(0),\n  v2(1),\n  v3(2)\n}\n\nVersionedSerial ::= SEQUENCE {\n  version [0] Version DEFAULT v1,\n  serialNumber INTEGER\n}\n\nEND\n";

export const negativeIntegerDefinition = "NegativeIntegerExample DEFINITIONS ::= BEGIN\n\nDelta ::= INTEGER {\n  lower(-129),\n  minusOne(-1),\n  zero(0),\n  upper(127)\n}\n\nSignedRecord ::= SEQUENCE {\n  delta Delta DEFAULT zero,\n  offset INTEGER\n}\n\nEND\n";

export const oidNamesDefinition = "OidNameExample DEFINITIONS ::= BEGIN\n\nAlgorithmIdentifier ::= SEQUENCE {\n  algorithm OBJECT IDENTIFIER,\n  parameters NULL OPTIONAL\n}\n\nEND\n";

export const personDefinition = "Example DEFINITIONS ::= BEGIN\n\nPerson ::= SEQUENCE {\n  name UTF8String,\n  age INTEGER OPTIONAL,\n  email IA5String OPTIONAL\n}\n\nEND\n";

export const pkiComponentsDefinition = "PkiComponents DEFINITIONS EXPLICIT TAGS ::= BEGIN\n\nVersion ::= INTEGER { v1(0), v2(1), v3(2) }\n\nCertificateSerialNumber ::= INTEGER\n\nAlgorithmIdentifier ::= SEQUENCE {\n  algorithm OBJECT IDENTIFIER,\n  parameters CHOICE { null NULL, namedCurve OBJECT IDENTIFIER } OPTIONAL\n}\n\nAttributeTypeAndValue ::= SEQUENCE {\n  type OBJECT IDENTIFIER,\n  value DirectoryString\n}\n\nDirectoryString ::= CHOICE {\n  utf8String UTF8String,\n  printableString PrintableString,\n  ia5String IA5String\n}\n\nRelativeDistinguishedName ::= SET OF AttributeTypeAndValue\n\nRDNSequence ::= SEQUENCE OF RelativeDistinguishedName\n\nName ::= CHOICE {\n  rdnSequence RDNSequence\n}\n\nTime ::= CHOICE {\n  utcTime UTCTime,\n  generalizedTime GeneralizedTime\n}\n\nValidity ::= SEQUENCE {\n  notBefore Time,\n  notAfter Time\n}\n\nSubjectPublicKeyInfo ::= SEQUENCE {\n  algorithm AlgorithmIdentifier,\n  subjectPublicKey BIT STRING\n}\n\nRSAPublicKey ::= SEQUENCE {\n  modulus INTEGER,\n  publicExponent INTEGER\n}\n\nDSA-Sig-Value ::= SEQUENCE {\n  r INTEGER,\n  s INTEGER\n}\n\nECDSA-Sig-Value ::= SEQUENCE {\n  r INTEGER,\n  s INTEGER\n}\n\nSignatureValue ::= BIT STRING\n\nExtension ::= SEQUENCE {\n  extnID OBJECT IDENTIFIER,\n  critical BOOLEAN DEFAULT FALSE,\n  extnValue OCTET STRING\n}\n\nExtensions ::= SEQUENCE OF Extension\n\nTBSCertificate ::= SEQUENCE {\n  version [0] EXPLICIT Version DEFAULT v1,\n  serialNumber CertificateSerialNumber,\n  signature AlgorithmIdentifier,\n  issuer Name,\n  validity Validity,\n  subject Name,\n  subjectPublicKeyInfo SubjectPublicKeyInfo,\n  issuerUniqueID [1] IMPLICIT BIT STRING OPTIONAL,\n  subjectUniqueID [2] IMPLICIT BIT STRING OPTIONAL,\n  extensions [3] EXPLICIT Extensions OPTIONAL\n}\n\nCertificate ::= SEQUENCE {\n  tbsCertificate TBSCertificate,\n  signatureAlgorithm AlgorithmIdentifier,\n  signatureValue SignatureValue\n}\n\nCertificationRequestInfo ::= SEQUENCE {\n  version INTEGER,\n  subject Name,\n  subjectPKInfo SubjectPublicKeyInfo,\n  attributes [0] IMPLICIT SET OF AttributeTypeAndValue OPTIONAL\n}\n\nCertificationRequest ::= SEQUENCE {\n  certificationRequestInfo CertificationRequestInfo,\n  signatureAlgorithm AlgorithmIdentifier,\n  signature SignatureValue\n}\n\nPrivateKeyInfo ::= SEQUENCE {\n  version INTEGER,\n  privateKeyAlgorithm AlgorithmIdentifier,\n  privateKey OCTET STRING,\n  attributes [0] IMPLICIT SET OF AttributeTypeAndValue OPTIONAL\n}\n\nContentInfo ::= SEQUENCE {\n  contentType OBJECT IDENTIFIER,\n  content [0] EXPLICIT OCTET STRING OPTIONAL\n}\n\nPkiBundle ::= SEQUENCE {\n  signature AlgorithmIdentifier,\n  issuer Name,\n  validity Validity,\n  subjectPublicKeyInfo SubjectPublicKeyInfo,\n  extension Extension OPTIONAL\n}\n\nEND\n";

export const taggedPersonDefinition = "ExampleTagged DEFINITIONS ::= BEGIN\n\nTaggedPerson ::= SEQUENCE {\n  name [0] EXPLICIT UTF8String,\n  age [1] IMPLICIT INTEGER OPTIONAL,\n  email [2] IMPLICIT IA5String OPTIONAL\n}\n\nEND\n";

export const x509VersionDefinition = "X509VersionExample DEFINITIONS ::= BEGIN\n\nVersion ::= INTEGER {\n  v1(0),\n  v2(1),\n  v3(2)\n}\n\nTBSCertificatePrefix ::= SEQUENCE {\n  version [0] EXPLICIT Version DEFAULT v1,\n  serialNumber INTEGER\n}\n\nEND\n";

export const binaryInputsInput = "{\n  \"payload\": { \"hex\": \"de ad be ef\" },\n  \"label\": { \"utf8\": \"hello\" },\n  \"flags\": { \"bytes\": { \"base64\": \"oA==\" }, \"unusedBits\": 5 }\n}\n";

export const defaultsAndEnumeratedInput = "{\n  \"enabled\": true,\n  \"retryCount\": 3,\n  \"status\": \"warning\",\n  \"note\": \"needs review\"\n}\n";

export const minimalCertificateInput = "{\n  \"tbsCertificate\": {\n    \"version\": \"v3\",\n    \"serialNumber\": 42,\n    \"signature\": {\n      \"algorithm\": \"sha256WithRSAEncryption\",\n      \"parameters\": null\n    },\n    \"issuer\": {\n      \"selected\": \"rdnSequence\",\n      \"value\": [\n        [\n          {\n            \"type\": \"commonName\",\n            \"value\": { \"selected\": \"utf8String\", \"value\": \"Example CA\" }\n          }\n        ]\n      ]\n    },\n    \"validity\": {\n      \"notBefore\": { \"selected\": \"utcTime\", \"value\": \"260520000000Z\" },\n      \"notAfter\": { \"selected\": \"utcTime\", \"value\": \"270520000000Z\" }\n    },\n    \"subject\": {\n      \"selected\": \"rdnSequence\",\n      \"value\": [\n        [\n          {\n            \"type\": \"commonName\",\n            \"value\": { \"selected\": \"utf8String\", \"value\": \"Example EE\" }\n          }\n        ]\n      ]\n    },\n    \"subjectPublicKeyInfo\": {\n      \"algorithm\": {\n        \"algorithm\": \"rsaEncryption\",\n        \"parameters\": null\n      },\n      \"subjectPublicKey\": { \"bytes\": { \"hex\": \"00\" }, \"unusedBits\": 0 }\n    },\n    \"extensions\": [\n      {\n        \"extnID\": \"basicConstraints\",\n        \"critical\": true,\n        \"extnValue\": { \"hex\": \"30030101ff\" }\n      }\n    ]\n  },\n  \"signatureAlgorithm\": {\n    \"algorithm\": \"sha256WithRSAEncryption\",\n    \"parameters\": null\n  },\n  \"signatureValue\": { \"bytes\": { \"hex\": \"deadbeef\" }, \"unusedBits\": 0 }\n}\n";

export const minimalCrlInput = "{\n  \"tbsCertList\": {\n    \"version\": \"v2\",\n    \"signature\": {\n      \"algorithm\": \"sha256WithRSAEncryption\",\n      \"parameters\": null\n    },\n    \"issuer\": {\n      \"selected\": \"rdnSequence\",\n      \"value\": [\n        [\n          {\n            \"type\": \"commonName\",\n            \"value\": { \"selected\": \"utf8String\", \"value\": \"Example CA\" }\n          }\n        ]\n      ]\n    },\n    \"thisUpdate\": { \"selected\": \"utcTime\", \"value\": \"260520000000Z\" },\n    \"nextUpdate\": { \"selected\": \"utcTime\", \"value\": \"260620000000Z\" },\n    \"revokedCertificates\": [\n      {\n        \"userCertificate\": 42,\n        \"revocationDate\": { \"selected\": \"utcTime\", \"value\": \"260521000000Z\" }\n      }\n    ],\n    \"crlExtensions\": [\n      {\n        \"extnID\": \"authorityKeyIdentifier\",\n        \"extnValue\": { \"hex\": \"3006800401020304\" }\n      }\n    ]\n  },\n  \"signatureAlgorithm\": {\n    \"algorithm\": \"sha256WithRSAEncryption\",\n    \"parameters\": null\n  },\n  \"signatureValue\": { \"bytes\": { \"hex\": \"0102030405060708\" }, \"unusedBits\": 0 }\n}\n";

export const minimalCsrInput = "{\n  \"certificationRequestInfo\": {\n    \"version\": 0,\n    \"subject\": {\n      \"selected\": \"rdnSequence\",\n      \"value\": [\n        [\n          {\n            \"type\": \"commonName\",\n            \"value\": { \"selected\": \"utf8String\", \"value\": \"Example EE\" }\n          }\n        ]\n      ]\n    },\n    \"subjectPublicKeyInfo\": {\n      \"algorithm\": {\n        \"algorithm\": \"rsaEncryption\",\n        \"parameters\": null\n      },\n      \"subjectPublicKey\": { \"bytes\": { \"hex\": \"00\" }, \"unusedBits\": 0 }\n    },\n    \"attributes\": [\n      {\n        \"type\": \"1.2.840.113549.1.9.7\",\n        \"values\": [{ \"utf8\": \"changeit\" }]\n      }\n    ]\n  },\n  \"signatureAlgorithm\": {\n    \"algorithm\": \"sha256WithRSAEncryption\",\n    \"parameters\": null\n  },\n  \"signature\": { \"bytes\": { \"hex\": \"010203040506\" }, \"unusedBits\": 0 }\n}\n";

export const minimalTbsCertificateInput = "{\n  \"version\": \"v3\",\n  \"serialNumber\": 42,\n  \"signature\": {\n    \"algorithm\": \"sha256WithRSAEncryption\",\n    \"parameters\": null\n  },\n  \"issuer\": {\n    \"selected\": \"rdnSequence\",\n    \"value\": [\n      [\n        {\n          \"type\": \"commonName\",\n          \"value\": { \"selected\": \"utf8String\", \"value\": \"Example CA\" }\n        }\n      ]\n    ]\n  },\n  \"validity\": {\n    \"notBefore\": { \"selected\": \"utcTime\", \"value\": \"260520000000Z\" },\n    \"notAfter\": { \"selected\": \"utcTime\", \"value\": \"270520000000Z\" }\n  },\n  \"subject\": {\n    \"selected\": \"rdnSequence\",\n    \"value\": [\n      [\n        {\n          \"type\": \"commonName\",\n          \"value\": { \"selected\": \"utf8String\", \"value\": \"Example EE\" }\n        }\n      ]\n    ]\n  },\n  \"subjectPublicKeyInfo\": {\n    \"algorithm\": {\n      \"algorithm\": \"rsaEncryption\",\n      \"parameters\": null\n    },\n    \"subjectPublicKey\": { \"bytes\": { \"hex\": \"00\" }, \"unusedBits\": 0 }\n  },\n  \"extensions\": [\n    {\n      \"extnID\": \"basicConstraints\",\n      \"critical\": true,\n      \"extnValue\": { \"hex\": \"30030101ff\" }\n    }\n  ]\n}\n";

export const negativeIntegerInput = "{\n  \"delta\": \"minusOne\",\n  \"offset\": -129\n}\n";

export const oidNamesInput = "{\n  \"algorithm\": \"sha256WithRSAEncryption\",\n  \"parameters\": null\n}\n";

export const personInput = "{\n  \"name\": \"Alice\",\n  \"age\": 42,\n  \"email\": \"alice@example.test\"\n}\n";

export const pkiComponentsInput = "{\n  \"signature\": {\n    \"algorithm\": \"sha256WithRSAEncryption\",\n    \"parameters\": { \"selected\": \"null\", \"value\": null }\n  },\n  \"issuer\": {\n    \"selected\": \"rdnSequence\",\n    \"value\": [\n      [\n        {\n          \"type\": \"commonName\",\n          \"value\": { \"selected\": \"utf8String\", \"value\": \"Example CA\" }\n        }\n      ]\n    ]\n  },\n  \"validity\": {\n    \"notBefore\": { \"selected\": \"utcTime\", \"value\": \"260520000000Z\" },\n    \"notAfter\": { \"selected\": \"utcTime\", \"value\": \"270520000000Z\" }\n  },\n  \"subjectPublicKeyInfo\": {\n    \"algorithm\": {\n      \"algorithm\": \"rsaEncryption\",\n      \"parameters\": { \"selected\": \"null\", \"value\": null }\n    },\n    \"subjectPublicKey\": { \"bytes\": { \"hex\": \"00\" }, \"unusedBits\": 0 }\n  },\n  \"extension\": {\n    \"extnID\": \"basicConstraints\",\n    \"critical\": true,\n    \"extnValue\": { \"hex\": \"30030101ff\" }\n  }\n}\n";

export const taggedPersonInput = "{\n  \"name\": \"Alice\",\n  \"age\": 42,\n  \"email\": \"alice@example.test\"\n}\n";

export const x509VersionInput = "{\n  \"version\": \"v3\",\n  \"serialNumber\": 12345\n}\n";
